[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
crucible_escrow = "Guq3DZZQ1PfAU49TG7WuEweSp6bjko8yVMdH3a3Hszfb"

[programs.devnet]
crucible_escrow = "Guq3DZZQ1PfAU49TG7WuEweSp6bjko8yVMdH3a3Hszfb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
